theme: jekyll-theme-minimal
title: Olaleye Ayoola
description:  B.Eng Student // Computer Vision Researcher

<p class="view"><a href="{{ site.github.owner_url }}">View My GitHub Profile </a><br><a href="https://twitter.com/Jonnygfrazer">View My Twitter Profile </a></p>
