theme: jekyll-theme-minimal
title: Olaleye Ayoola
description: Embedded Firmware Engineer
logo: https://user-images.githubusercontent.com/52134849/102813441-17b29880-43c9-11eb-8f33-be0775acdab2.jpeg

